### ISSUE TITLE
手机端样式

### ISSUE THREAD

**Issue by enlt** [JLinMr/Mini-Cover#4]
感谢开发MiniCover

只是手机端的样式有点怪，不知道是否考虑改改

**Comment by JLinMr** [comment]
手机端各种操作都不方便，这个工具主要还是PC端使用的
![1727773328335](https://github.com/user-attachments/assets/8d5f6ed8-f39f-4395-adad-a30ebdd41901)
如果样式有些问题，可以调整一下缩放
