### ISSUE TITLE
怎么更改尺寸

### ISSUE THREAD

**Issue by OP404OP** [JLinMr/Mini-Cover#7]
你好 怎么更改固定的尺寸 或 前端可以输入长宽

**Comment by JLinMr** [comment]
> 你好 怎么更改固定的尺寸 或 前端可以输入长宽

前端暂时没有添加这个功能，你可以自行部署的时候设置一下
文件为 `src/components/CoverGenerator.vue`中的
`<canvas id="canvasPreview" width="1000" height="500"></canvas>`
width="1000" height="500"为长和高

**Comment by OP404OP** [comment]
> > 你好 怎么更改固定的尺寸 或 前端可以输入长宽
> 
> 前端暂时没有添加这个功能，你可以自行部署的时候设置一下 文件为 `src/components/CoverGenerator.vue`中的 `<canvas id="canvasPreview" width="1000" height="500"></canvas>` width="1000" height="500"为宽和高

谢谢 我尝试了修改之后，前端虽然尺寸变了，但是一些其他的功能放的位置没有变，比如图标 水印，好像还是在原来的1000X500所设定的位置，没有自动适应到新的尺寸背景图的中心。

**Comment by JLinMr** [comment]
抱歉是我的疏忽，还需要更改`src/assets/script.js`中的
第33行到36行中的`(1000, 500)`

```
export const { canvas: bgCanvas, ctx: bgCtx } = createCanvas(1000, 500);
export const { canvas: textCanvas, ctx: textCtx } = createCanvas(1000, 500);
export const { canvas: watermarkCanvas, ctx: watermarkCtx } = createCanvas(1000, 500);
export const { canvas: squareCanvas, ctx: squareCtx } = createCanvas(1000, 500);
```

调增后网页样式会发生变化

**Comment by OP404OP** [comment]
> 抱歉是我的疏忽，还需要更改`src/assets/script.js`中的 第33行到36行中的`(1000, 500)`
> 
> ```
> export const { canvas: bgCanvas, ctx: bgCtx } = createCanvas(1000, 500);
> export const { canvas: textCanvas, ctx: textCtx } = createCanvas(1000, 500);
> export const { canvas: watermarkCanvas, ctx: watermarkCtx } = createCanvas(1000, 500);
> export const { canvas: squareCanvas, ctx: squareCtx } = createCanvas(1000, 500);
> ```
> 
> 调增后网页样式会发生变化

谢谢开源，谢谢回复。稍后我试试。

**Comment by JLinMr** [comment]
好的
