### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mowang2024** [JLinMr/Mini-Cover#9]
请问可不可以在根目录下创建一个config文件，然后默认的一些配置可以写到这个配置文件中，比如默认的标题，水印文字还有字体名和读取的字体css文件

**Comment by mowang2024** [comment]
js对于我这种新手来说不太友好，而且现在加载的几种字体速度太慢了，影响网页的生成

**Comment by JLinMr** [comment]
除了全局字体，其它字体是点开之后动态加载的

**Comment by JLinMr** [comment]
> 请问可不可以在根目录下创建一个config文件，然后默认的一些配置可以写到这个配置文件中，比如默认的标题，水印文字还有字体名和读取的字体css文件

修改了一下，应该可以满足你说的这个了

**Comment by mowang2024** [comment]
万分感谢

**Comment by mowang2024** [comment]
使用文档的教程构建的还是以前的，是不是有什么没改啊，纯新手，见谅 哈哈哈

**Comment by mowang2024** [comment]
哦哦，搞定了，要先修改文件内容再构建 哈哈哈
